version: "3"
services:
  nginx-proxy:
    image: mikenoethiger/customized-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  customized-proxy:
    external:
      name: customized-proxy
